### ISSUE TITLE
Platformio Environment to compile the code

### ISSUE THREAD

**Issue by itgenmar** [kscholty/SmartShuntINA226#2]
Could you help me to setup the environment to be able to compile ?

I am getting this error :

Processing release_nodemcu (board: nodemcuv2; framework: arduino; platform: espressif8266)
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif8266/nodemcuv2.html
PLATFORM: Espressif 8266 (4.2.1) > NodeMCU 1.0 (ESP-12E Module)
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
PACKAGES:
 - framework-arduinoespressif8266 @ 3.30102.0 (3.1.2)
 - tool-esptool @ 1.413.0 (4.13)
 - tool-esptoolpy @ 1.30000.201119 (3.0.0)
 - toolchain-xtensa @ 2.100300.220621 (10.3.0)
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ deep, Compatibility ~ soft
Found 42 compatible libraries
Scanning dependencies...
Dependency Graph
|-- INA226Lib @ 1.1.3
|-- modbus-esp8266 @ 4.1.0
|-- RingBuffer @ 1.0.4
|-- IotWebConf @ 3.2.1
|-- Wire @ 1.0
|-- ArduinoOTA @ 1.0
|-- DNSServer @ 1.1.1
|-- ESP8266WiFi @ 1.0
Building in debug mode
Compiling .pio\build\release_nodemcu\src\sensorHandling.cpp.o
Archiving .pio\build\release_nodemcu\lib1d3\libESP8266WiFi.a
Archiving .pio\build\release_nodemcu\libc99\libESP8266mDNS.a
Archiving .pio\build\release_nodemcu\libf47\libDNSServer.a
Compiling .pio\build\release_nodemcu\libbaf\ESP8266WebServer\detail\mimetable.cpp.o
Compiling .pio\build\release_nodemcu\lib84f\IotWebConf\IotWebConf.cpp.o
Compiling .pio\build\release_nodemcu\lib84f\IotWebConf\IotWebConfMultipleWifi.cpp.o
Compiling .pio\build\release_nodemcu\lib84f\IotWebConf\IotWebConfOptionalGroup.cpp.o
Compiling .pio\build\release_nodemcu\lib84f\IotWebConf\IotWebConfParameter.cpp.o
Compiling .pio\build\release_nodemcu\lib813\ArduinoOTA\ArduinoOTA.cpp.o
Archiving .pio\build\release_nodemcu\libFrameworkArduinoVariant.a
Compiling .pio\build\release_nodemcu\FrameworkArduino\Crypto.cpp.o
Compiling .pio\build\release_nodemcu\FrameworkArduino\Esp-frag.cpp.o
Compiling .pio\build\release_nodemcu\FrameworkArduino\Esp-version.cpp.o
Compiling .pio\build\release_nodemcu\FrameworkArduino\Esp.cpp.o
Compiling .pio\build\release_nodemcu\FrameworkArduino\FS.cpp.o
Archiving .pio\build\release_nodemcu\libbaf\libESP8266WebServer.a
Compiling .pio\build\release_nodemcu\FrameworkArduino\FSnoop.cpp.o
src\sensorHandling.cpp: In function 'void sensorLoop()':
src\sensorHandling.cpp:330:32: error: 'class INA226' has no member named 'isConversionReady'
  330 |     while (alertCounter && ina.isConversionReady()) {
      |                                ^~~~~~~~~~~~~~~~~
*** [.pio\build\release_nodemcu\src\sensorHandling.cpp.o] Error 1
========================================================================================== [FAILED] Took 4.68 seconds ==========================================================================================
Environment      Status    Duration
---------------  --------  ------------
release_nodemcu  FAILED    00:00:04.684
==================================================================================== 1 failed, 0 succeeded in 00:00:04.684 ==================================================================================== 

 *  The terminal process "C:\Users\itgenmar\.platformio\penv\Scripts\platformio.exe 'debug'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it. 

**And this is my platformio.ini** 

; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = release_nodemcu

[env]
framework = arduino
lib_ldf_mode = deep
lib_deps = 
	emelianov/modbus-esp8266
	locoduino/RingBuffer
	prampec/IotWebConf
	peterus/INA226Lib@^1.1.3
monitor_speed = 19200
monitor_port = COM4
monitor_filters = esp8266_exception_decoder
platform = espressif8266
board_build.partitions = min_spiffs.csv
upload_protocol = esptool
build_flags = -DIOTWEBCONF_DEBUG_DISABLED -O3

[env:release_nodemcu]
board = nodemcuv2
build_type = release
upload_port = COM7
lib_deps = 
	peterus/INA226Lib@^1.1.3
	emelianov/modbus-esp8266@^4.1.0
	locoduino/RingBuffer@^1.0.4
	prampec/IotWebConf@^3.2.1

[env:release_ota_nodemcu]
board = nodemcuv2
build_type = release
upload_port = 192.168.100.182
upload_protocol = espota
lib_deps = 
	peterus/INA226Lib@^1.1.3
	emelianov/modbus-esp8266@^4.1.0
	locoduino/RingBuffer@^1.0.4
	prampec/IotWebConf@^3.2.1

[env:release_d1]
board = d1_mini
build_type = release
upload_port = COM7
lib_deps = 
	peterus/INA226Lib@^1.1.3
	emelianov/modbus-esp8266@^4.1.0
	locoduino/RingBuffer@^1.0.4
	prampec/IotWebConf@^3.2.1

[env:release_d1_ota]
board = d1_mini
build_type = release
upload_port = 192.168.100.178
upload_protocol = espota
lib_deps = 
	peterus/INA226Lib@^1.1.3
	emelianov/modbus-esp8266@^4.1.0
	locoduino/RingBuffer@^1.0.4
	prampec/IotWebConf@^3.2.1

[env:release_s2]
platform = espressif32
board = lolin_s2_mini
build_type = release
build_flags = -DIOTWEBCONF_DEBUG_DISABLED -O3
monitor_speed = 115200
lib_deps = 
	peterus/INA226Lib@^1.1.3
	emelianov/modbus-esp8266@^4.1.0
	locoduino/RingBuffer@^1.0.4
	prampec/IotWebConf@^3.2.1

[env:release_s2_ota]
platform = espressif32
board = lolin_s2_mini
build_type = release
upload_port = 192.168.100.198
upload_protocol = espota
build_flags = -DIOTWEBCONF_DEBUG_DISABLED -O3
lib_deps = 
	peterus/INA226Lib@^1.1.3
	emelianov/modbus-esp8266@^4.1.0
	locoduino/RingBuffer@^1.0.4
	prampec/IotWebConf@^3.2.1

**Comment by kscholty** [comment]
You are probably using the wrong INA226 lib. V1.1.3 is too old. You should use the head code in peter's repository https://github.com/peterus/INA226Lib
You can check it out into the lib subfolder in the project or somewhere else where it will be found.
You sould remove the dependency in the platformio.ini to the 1.1.3 version. This one will not work.

**Comment by itgenmar** [comment]
Thank you very much. I have managed to create a profile for Esp32wroom. Now
I am waiting for the ina226 from China.

thank you again

**Comment by itgenmar** [comment]
Happy New Year, 

I got the S2 mini [https://www.studiopieters.nl/esp32-s2/](https://www.studiopieters.nl/esp32-s2/) but i have no serial debugger on USB and I can't find the serial pins on it? Could you point me in the right direction ?

Thank you

**Comment by itgenmar** [comment]
39 tx 40 rx

**Comment by kscholty** [comment]
> 39 tx 40 rx
That's not correct. 
The pins are `TX=39` and `RX=37`
This is made so that the pinout is identical to a D1 mini board.
