### ISSUE TITLE
Options for smaller batteries

### ISSUE THREAD

**Issue by mrpeter322** [kscholty/SmartShuntINA226#6]
Hi. Nust wondering if the R has any other meaning as lowering the initial 16s lifepo4 voltage down to around 38V. As from my understanding you dont need Rs while using 12 or 24V (4 or 16S lifepo4) systems as this voltage is within range. Right? Can this be exluded for this systems?

If yes, are you able to edit the docs or just add some node under schematic so that other dont do this for smaller system? As lowering voltage for 12V system mean going down to around 6V in this case.

**Comment by kscholty** [comment]
You are absolutely right. You need it only for systems that exceed 36V. This is why the documentation states:

_"If you have a 48V System, be aware of the fact that the INA226 does only support voltages up to 36V (40V max). You need a voltage divider to make shure your sensor is not destroyed."_

**Comment by mrpeter322** [comment]
Thanks for confirmation. Enjoy!
