### ISSUE TITLE
Does not compile Platformio

### ISSUE THREAD

**Issue by BisSpaeterDannnoch** [kscholty/SmartShuntINA226#7]
Hi, what a nice project.

I have problemes compiling the code. May I please ask you to verify if it does in your enviroment (and me being dump)?
Maybe an update gone wild after your last release...

In case in does, may ask you to upload a WemosD1 .bin file, so that I can go on with my project, until i sort out what's wrong with my enviroment.

Thank you very much and have a good time - Sven

Processing release_d1 (board: d1_mini; framework: arduino; platform: espressif8266)
---------------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif8266/d1_mini.html
PLATFORM: Espressif 8266 (4.2.1) > WeMos D1 R2 and mini
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
PACKAGES:
 - framework-arduinoespressif8266 @ 3.30102.0 (3.1.2)
 - tool-esptool @ 1.413.0 (4.13)
 - tool-esptoolpy @ 1.30000.201119 (3.0.0)
 - toolchain-xtensa @ 2.100300.220621 (10.3.0)
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ deep+, Compatibility ~ soft
Found 41 compatible libraries
Scanning dependencies...
Dependency Graph
|-- modbus-esp8266 @ 4.1.0
|-- INA226 @ 0.6.0
|-- Wire @ 1.0
|-- IotWebConf @ 3.2.1
|-- ESP8266SdFat @ 2.1.1
|-- ArduinoOTA @ 1.0
|-- ESP8266WiFi @ 1.0
|-- ESP8266HTTPUpdateServer @ 1.0
|-- ESP8266WebServer @ 1.0
|-- DNSServer @ 1.1.1
Building in release mode
Compiling .pio\build\release_d1\src\main.cpp.o
Compiling .pio\build\release_d1\src\modbusHandling.cpp.o
Compiling .pio\build\release_d1\src\sensorHandling.cpp.o
Compiling .pio\build\release_d1\src\statusHandling.cpp.o
src\sensorHandling.cpp:37:23: error: no matching function for call to 'INA226::INA226(TwoWire&)'
   37 | static INA226 ina(Wire);
      |                       ^
In file included from src\sensorHandling.cpp:4:
.pio\libdeps\release_d1\INA226/INA226.h:79:12: note: candidate: 'INA226::INA226(uint8_t, TwoWire*)'
   79 |   explicit INA226(const uint8_t address, TwoWire *wire = &Wire);
      |            ^~~~~~
.pio\libdeps\release_d1\INA226/INA226.h:79:33: note:   no known conversion for argument 1 from 'TwoWire' to 'uint8_t' {aka 'unsigned char'}
   79 |   explicit INA226(const uint8_t address, TwoWire *wire = &Wire);
      |                   ~~~~~~~~~~~~~~^~~~~~~
.pio\libdeps\release_d1\INA226/INA226.h:75:7: note: candidate: 'constexpr INA226::INA226(const INA226&)'
   75 | class INA226
      |       ^~~~~~
.pio\libdeps\release_d1\INA226/INA226.h:75:7: note:   no known conversion for argument 1 from 'TwoWire' to 'const INA226&'
.pio\libdeps\release_d1\INA226/INA226.h:75:7: note: candidate: 'constexpr INA226::INA226(INA226&&)'
.pio\libdeps\release_d1\INA226/INA226.h:75:7: note:   no known conversion for argument 1 from 'TwoWire' to 'INA226&&'
src\statusHandling.cpp: In member function 'void BatteryStatus::updateConsumption(float, float, uint16_t)':
src\statusHandling.cpp:60:27: error: 'class RingBuf<float, 60>' has no member named 'isFull'
   60 |         if (currentValues.isFull()) {
      |                           ^~~~~~
src\statusHandling.cpp:62:25: error: 'class RingBuf<float, 60>' has no member named 'pop'
   62 |           currentValues.pop(oldVal);
      |                         ^~~
src\statusHandling.cpp:65:23: error: 'class RingBuf<float, 60>' has no member named 'push'
   65 |         currentValues.push(current);
      |                       ^~~~
src\statusHandling.cpp:70:22: error: 'class RingBuf<float, 60>' has no member named 'isEmpty'
   70 |     if(currentValues.isEmpty()) {
      |                      ^~~~~~~

**Comment by kscholty** [comment]
Du hast die falsche  Version der INA226 Lib. Du musst die von mir hier nehmen, wie im Readme beschrieben.
Ich habe aber mal aktuelle Binaries hochgeladen. Das Release v1.1.0 enthält die aktuellste Version.
Viel Spaß.

**Comment by BisSpaeterDannnoch** [comment]
Du bist so gut. Vielen Dank und eine gute Zeit!

kscholty ***@***.***> schrieb am Fr., 12. Juli 2024, 20:42:

**Comment by BisSpaeterDannnoch** [comment]
danke noch einmal.  Es lebt jetzt auf einem  D1 mini lite, hängt in meinem Netz und und belohnt mich alle 5 sec mit einem led-flash :) Nun warte ich auf die restlichen Bauteile von Ali.
Gute Zeit.
