### ISSUE TITLE
DVCC Compatibility

### ISSUE THREAD

**Issue by oa4ajp** [kscholty/SmartShuntINA226#8]
Can we use DVCC with Venus OS and the Smartshunt INA226?
Does it  show the battery status on the GUI screen ?

![image](https://github.com/user-attachments/assets/58f9997b-1a86-4441-b9a9-88fc559bdd96)

Regards
Alfred

**Comment by kscholty** [comment]
Yes, it does. For Venus OS it's just a Smart -Shunt.
You just have to make sure that it's selected as the active battery monitor.
