### ISSUE TITLE
Some fields of the Text protocol are not yet filled correctly

### ISSUE THREAD

**Issue by oa4ajp** [kscholty/SmartShuntINA226#9]
Hello, 

**I have read this on the project readme:**
Victron VE.direct Text and Hex protocols in order to function as a Battery Monitor. The Hex protocol is only implemented as far as it's required for startup. Furthermore, some fields of the **Text protocol are not yet filled correctly**.

Does it mean that the smart shunt INA226 has limitations or partial functionality with Venus OS?

I'm asking before start building your design.

Regards
Alfredo Mendiola

**Comment by kscholty** [comment]
The statistics are not complete and they are not persistent. 
It doesn't have any relay support and you can't configure any alarms.  
That's the only restrictions I remember from the top of my head.
